version: '3'

services:
  db:
    image: postgres
    container_name: bookstore_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - mynetwork
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mynetwork
networks:
  mynetwork: