# Generated by Django 5.0.6 on 2024-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open Cart'), ('closed', 'Closed Cart')], default='open', max_length=10),
        ),
    ]
